### PR TITLE
ENH added new build

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
Are the URLs the same?

**Comment by beckermr** [comment]
Not yet. I can add redirects but have not gotten to it yet.

**Comment by beckermr** [comment]
It's pretty now.

blog_gif

**Comment by beckermr** [comment]
After this PR, i'll need to setup travis to build and then push to the master with the actual blog.

**Pull request merged**
