### PR TITLE
CFEP9 blog post

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@conda-forge/core thoughts, edits, comments (please feel free to push to this)

**Comment by ocefpaf** [comment]
@CJ-Wright do you want to add some blog platform for that markdown or should I just experiment with a simple jekyll build?

**Comment by CJ-Wright** [comment]
I think the platform is out of scope for this PR. Have no preference for platform.

**Comment by ocefpaf** [comment]
> I think the platform is out of scope for this PR. Have no preference for platform.

We'll, we need one to build it, right? I'm playing with Jekyll and I should have something soon.

**Comment by ocefpaf** [comment]
OK. Let's merge this as-is and I'll add the jekyll stuff using this PR as a first post. I may need to add the front-matter later but I'll ping you on the PR doing that.

**Comment by jakirkham** [comment]
Thanks @CJ-Wright both for all this work and this write-up! 😄

**Pull request merged**
