### PR TITLE
R4 retrospective post

### PR DESCRIPTION
**Pull request by CJ-Wright**
@beckermr please feel to add thoughts, edits, etc. (and your name to the authorship if you want)

### CODE REVIEW

**Comment by beckermr** [comment]
I have a pr open on your fork with edits.

**Review by beckermr — COMMENTED** [review]
Do we need to vote on merging this or can I go ahead?

**Comment by beckermr** [comment]
@conda-forge/core any comments here?

**Comment by jakirkham** [comment]
cc @xhochy @mingwandroid

**Comment by jakirkham** [comment]
> Do we need to vote on merging this or can I go ahead?

I don't think there is anything so formal here. Might be good to get Uwe and Ray's thoughts though (copied above).

**Comment by beckermr** [comment]
Alright. I am going to merge this. We can add changes later if ppl have comments.

**Pull request merged**
